services:
  db: 
    image: mysql:latest
    container_name: mysql_site
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d/
      

  backend:
    build:
      context: ./backend
    container_name: backend_site
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend_site
    depends_on:
      - db
      - backend
    ports:
      - 8081:3000
    # restart: unless-stopped
    volumes:
      - ./frontend:/app
